### ISSUE TITLE
Make models parcelable

### ISSUE THREAD

**Issue by ivamluz** [Karumi/MarvelApiClientAndroid#12]
It would be nice to have models to implement Parcelable, so they can be passed as arguments to intents.

**Comment by pedrovgs** [comment]
Hi @ivamluz, thanks for your issue. This library can be used in java projects, not just in Android projects and that's why we try to do not couple the library implementation to the Android SDK. If we change the project to use the `Parcelable` interface we are going to couple the library to the Android SDK.

If you want to pass an instance as a parcelable you can always create a wrapper or use inheritance as follows:

``` java
public class ParcelableSuperHero extends SuperHero implements Parcelable {
   ....
}
```

or 

``` java
public class ParcelableSuperHero implements Parcelable {
   private final SuperHero superHero;

   public ParcelableSuperHero(SuperHero superHero) {
      this.superHero = superHero;
   }

   ......

}
```

Thoughts @flipper83?

**Comment by flipper83** [comment]
Sorry I have been out of office and I can not respond it.

Makes parcelable the model are out of scope of this project, we want keep the library small, simple and Java compatible. Parcelable is member of Android SDK.

As @pedrovgs said, you can create a wrapper over the classes, or you can create a fork only for android cases.

Sorry.

**Comment by ivamluz** [comment]
No problem, guys. Thanks for your inputs.
